# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.9.0
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: npm install
      - run:
          name: tests
          command: npm test
      - run:
          name: build-executable
          command: npm run compile
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Configure git user
          command: |
            git config --global user.email "jupvillegasgo@unal.edu.co" && git config --global user.name "MrPauL91"
      # - run:
      #     name: Make deployment commit
      #     command: |
      #       git commit -am "A new version has been deployed"
     # - deploy:
       #   command: npm run compile
            
workflows:
  version: 2
  everything:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
